import type { TradePlannerProps } from "./types.js";

export const DEMO_TRADE_PLANNER_PROPS: TradePlannerProps = {
  current_week_index: 4,
  current_date: "2020-02-03",
  max_actions_per_step: 3,
  remaining_action_slots: 3,
  available_tickers: ["AAPL", "AMZN", "GOOGL", "MSFT", "NVDA"],
  current_cash: 62_450.25,
  current_total_nav: 100_000,
  current_batch: [],
  holdings: [
    {
      ticker: "AAPL",
      shares: 120,
      average_cost: 142.5,
      market_value: 17_291.14,
      weight: 0.1729,
      active_stop: 135,
      current_close: 144.09,
    },
    {
      ticker: "MSFT",
      shares: 80,
      average_cost: 238.2,
      market_value: 19_460.73,
      weight: 0.1946,
      current_close: 243.26,
    },
    {
      ticker: "NVDA",
      shares: 35,
      average_cost: 205.4,
      market_value: 7_733.93,
      weight: 0.0773,
      current_close: 220.97,
    },
  ],
  active_stops: { AAPL: 135 },
  pending_liquidations: [],
  ticker_options: {
    buy: ["AAPL", "AMZN", "GOOGL", "MSFT", "NVDA"],
    sell: ["AAPL", "MSFT", "NVDA"],
    reduce: ["AAPL", "MSFT", "NVDA"],
    set_stop: ["MSFT", "NVDA"],
    remove_stop: ["AAPL"],
  },
  close_prices: {
    AAPL: 144.09,
    AMZN: 3079.55,
    GOOGL: 2874.81,
    MSFT: 243.26,
    NVDA: 220.97,
  },
  plan_impact: {
    estimated_spend: 0,
    estimated_proceeds: 0,
    estimated_transaction_costs: 0,
    estimated_remaining_cash: 62_450.25,
    estimated_positions_after: 3,
    estimated_invested_after: 37_549.75,
    projected_max_weight: 0.1946,
    warnings: [],
    notes: ["Standalone demo mode. Run the Streamlit app locally for live sessions."],
  },
};
